name = "knue-event-harvester-cf"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[triggers]
crons = ["5 0-10 * * 1-5"]

[[kv_namespaces]]
binding = "PROCESSED_STORE"
id = "68a5f081c9544cbe975b7de5f29118b1"

[vars]
PREVIEW_PARSER_BASE = "https://knue-www-preview-parser-cf.kangdongouk.workers.dev"
OPENAI_CONTENT_MODEL = "gpt-4o-mini"
OPENAI_VISION_MODEL = "gpt-4o-mini"
SIMILARITY_THRESHOLD = "0.85"
LOOKBACK_DAYS = "30"
GOOGLE_CALENDAR_ID = "b71b5c37386baf51a196b6a1de3013726b55f51aa571d583f477cdacaf12bd5d@group.calendar.google.com"

# Telegram notification settings
# Set via: npx wrangler secret put TELEGRAM_BOT_TOKEN
# Set via: npx wrangler secret put TELEGRAM_USER_ID
# Format: TELEGRAM_BOT_TOKEN = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
# Format: TELEGRAM_USER_ID = "987654321"

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1